version: '3'

services:
  api_rinha_db:
    image: postgres
    command: postgres -c 'max_connections=1000'
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: app_user
      POSTGRES_DB: app_db
      POSTGRES_PASSWORD: app_password
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: "0.13"
          memory: "140MB"

  fastapirinha1:
    # image: apirinha:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: fastapirinha1
    entrypoint: ./entrypoint.sh
    volumes:
      - sockets:/fastapi/tmp/sockets
    # ports:
    #   - "8081:8080"
    depends_on:
      - api_rinha_db
    environment:
      DATABASE_URL: postgresql://app_user:app_password@api_rinha_db:5432/app_db
      BIND: unix:/fastapi/tmp/sockets/fastapirinha1.sock
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  fastapirinha2:
    # image: apirinha:latest
    build:
      context: .
      dockerfile: Dockerfile
    hostname: fastapirinha2
    entrypoint: ./entrypoint.sh
    volumes:
      - sockets:/fastapi/tmp/sockets
    # ports:
    #   - "8082:8080"
    depends_on:
      - api_rinha_db
    environment:
      DATABASE_URL: postgresql://app_user:app_password@api_rinha_db:5432/app_db
      BIND: unix:/fastapi/tmp/sockets/fastapirinha2.sock
    deploy:
      resources:
        limits:
          cpus: "0.6"
          memory: "200MB"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - sockets:/fastapi/tmp/sockets
    ports:
      - "9999:9999"
    depends_on:
      - fastapirinha1
      - fastapirinha2
    deploy:
      resources:
        limits:
          cpus: "0.17"
          memory: "10MB"

volumes:
  pgdata:
  sockets:

networks:
  default:
    driver: bridge
    name: rinha-backend-2024