"""add fk in transactions

Revision ID: dfaae8c27a54
Revises: dc582797aaa0
Create Date: 2024-02-10 18:21:55.167305

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfaae8c27a54'
down_revision: Union[str, None] = 'dc582797aaa0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transactions', sa.Column('client_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'transactions', 'client', ['client_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'client_id')
    # ### end Alembic commands ###
